### PR TITLE
second review

### PR DESCRIPTION
**Pull request by Amalcxc**
Add the "Editor's picks" section using the tag

### CODE REVIEW

**Review by SmithVyne — CHANGES_REQUESTED** [review]
### Invalid Pull Request ❌ 🤕 
Hello there, I can see you are beginning to understand how this works, but currently your pull request title and description are not as descriptive/professional as they should be. Please improve them by making the title more descriptive/relatable and the description should contain what you have achieved or the changes you have made in the project.

You can also reach out to me on slack, @SmithVyne if you have any other questions.

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
**Hi Amai!
Great job so far on this milestone:clap::clap:. The project looks very much like the original. Keep up the good work. Let's quickly make a few changes to get the milestone approved.**

**Mandatory requirement**

- [x] It uses [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)).Kindly fix this. 

[ Optional]
 - There are three PR's currently opened on the project repository. Only one PR is needed. Close the two not required.
 - Naming the html file as newyork.html instead of index.html is actually not following best practice. This is because index.html is the default file a server looks for when in a directory. You can do more research on it. 
 
Make the above required changes and when you are ready, request another review.
Kindly drop your questions here and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Required Changes :yellow_circle: : 
Hello Amal :wave:

You have made good progress and your project shows you did a lot of work. 
But for this project to be approved, you need to work on mandatory requirements requested by the TSEs :arrow_up: . 

## Manadtory: 
- [x]  It uses \<aside> tag for Editor's picks section on the righmost side. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)).Kindly fix this.

## Suggestions:

- There are three PR's currently opened on the project repository. Only one PR is needed. Close the two not required.
- Naming the html file as newyork.html instead of index.html is actually not following best practice. This is because index.html is the default file a server looks for when in a directory. You can do more research on it.

__Kindly make the necessary changes and submit another code review request.__
### if you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer:

**Review by ioilmio — CHANGES_REQUESTED** [review]
# Hello @Amalcxc  👋🏽  Good Job! 💪🏽 

### The project's goal is to clone the original page in the best possible way, this implies taking care of all the sections and positioning them accordingly, in general, these first projects are also meant to help you understand best practices you will use trough out the program like the correct use of Git and GitHub, linters and workflow.
### So please fix the following:

### Required changes ♻️ 
- ### Linters are not running in GitHub Action
- ### Add and commit your changes and then push them to GitHub
- ### Use `aside` for the Editor's pick section, modify the HTML file
- ### NewYork Times Logo is also a link
image

- ### This section doesn't resemble the original page, image is oversized
image

- ### Use caption for image text related 
image


- ### Main content should be a little bit more wide
- ### You are missing this section with a button from the original page
image

- ### Fix this section text is overlapping with borders
image

- ### You are not using GIT POWER take a look at both section of this [interactive tutorial](https://learngitbranching.js.org/) to finally use git push and pull in an effective way

*For any doubt or clarification contact me on slack @illuminatosalvatore*
- ## Happy Coding 💻

**Comment by Amalcxc** [comment]
the new code is in the one-page-article branch, please review that one thnaks

**Review by krys2fa — CHANGES_REQUESTED** [review]
## Nicely done @Amalcxc  👏 
Your project displays good use of semantic HTML as well as CSS classes. 💪 

Just a few more adjustments to complete the project. They can be seen below:
### Status: Changes Required ♻️ 

**NB:** Review was done at a screen size of **1440px**. Kindly state your preferred screen size if your clone displays better on your machine.

- [x] [REQUIRED] Your 'Live Demo' link should point to a live version of your application and not a copy of your README.
- [x] [REQUIRED]  The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

Please request another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 

Great job @Amalcxc, and thanks for making the required changes :hammer: :wrench: by the previous TSE's.

Now you can merge, your project is approved :checkered_flag: 

## Happy Coding :tophat:

**Pull request closed without merging**
